/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package des;

import javax.swing.ImageIcon;

/**
 *
 * @author azure Tran
 */
public class DES_ENCYPT_PROGRESS extends javax.swing.JFrame {

    /**
     * Creates new form DES_ENCYPT_PROGRESS
     */
    ImageIcon icon;
    public DES_ENCYPT_PROGRESS() {
        initComponents();
           setTitle("ĐÔ ÁN CUỐI KÌ NHÓM 3");
      
        icon =new ImageIcon("image/icon.jpg");
         setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRound2 = new javax.swing.JTextField();
        txtRound3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRound4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRound5 = new javax.swing.JTextField();
        txtRound6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRound7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRound8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRound9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRound10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRound11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRound12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRound13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRound14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtRound15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRound16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtRound1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("SHOW DETAILS PROGRESS OF ENCRYPTION DES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 23, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("ROUND 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("ROUND 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(txtRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 430, 41));
        getContentPane().add(txtRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 430, 41));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("ROUND 3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        txtRound4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRound4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 430, 41));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("ROUND 4");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("ROUND 5");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(txtRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 430, 41));
        getContentPane().add(txtRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 430, 41));

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("ROUND 6");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));
        getContentPane().add(txtRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 430, 41));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("ROUND 7");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        getContentPane().add(txtRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 430, 41));

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("ROUND 8");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));
        getContentPane().add(txtRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 430, 41));

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("ROUND 9");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        getContentPane().add(txtRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 430, 41));

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("ROUND 10");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));
        getContentPane().add(txtRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 430, 41));

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("ROUND 11");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));
        getContentPane().add(txtRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 430, 41));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("ROUND 12");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));
        getContentPane().add(txtRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 430, 41));

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("ROUND 13");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));
        getContentPane().add(txtRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 430, 41));

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("ROUND 14");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, -1, -1));
        getContentPane().add(txtRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 430, 41));

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("ROUND 15");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));
        getContentPane().add(txtRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 430, 41));

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("ROUND 16");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, -1, -1));
        getContentPane().add(txtRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 430, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRound4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRound4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRound4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DES_ENCYPT_PROGRESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DES_ENCYPT_PROGRESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DES_ENCYPT_PROGRESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DES_ENCYPT_PROGRESS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DES_ENCYPT_PROGRESS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtRound1;
    private javax.swing.JTextField txtRound10;
    private javax.swing.JTextField txtRound11;
    private javax.swing.JTextField txtRound12;
    private javax.swing.JTextField txtRound13;
    private javax.swing.JTextField txtRound14;
    private javax.swing.JTextField txtRound15;
    private javax.swing.JTextField txtRound16;
    private javax.swing.JTextField txtRound2;
    private javax.swing.JTextField txtRound3;
    private javax.swing.JTextField txtRound4;
    private javax.swing.JTextField txtRound5;
    private javax.swing.JTextField txtRound6;
    private javax.swing.JTextField txtRound7;
    private javax.swing.JTextField txtRound8;
    private javax.swing.JTextField txtRound9;
    // End of variables declaration//GEN-END:variables
}
